// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6dvZJ2mGkuo55tY9DAJQGMD2-Jn9Kz38',
    appId: '1:355582024496:web:64c1833265204efccf86f5',
    messagingSenderId: '355582024496',
    projectId: 'sushi-app-e4048',
    authDomain: 'sushi-app-e4048.firebaseapp.com',
    storageBucket: 'sushi-app-e4048.appspot.com',
    measurementId: 'G-4RENLHMSG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLXi2e0dpvUJUtCBD10-002kuIEv6KAm8',
    appId: '1:355582024496:android:71fcbb880185fc23cf86f5',
    messagingSenderId: '355582024496',
    projectId: 'sushi-app-e4048',
    storageBucket: 'sushi-app-e4048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOoum3c2McYxVJAdRTtilbpHM3xXCERJg',
    appId: '1:355582024496:ios:91fc7cb505fd0f32cf86f5',
    messagingSenderId: '355582024496',
    projectId: 'sushi-app-e4048',
    storageBucket: 'sushi-app-e4048.appspot.com',
    iosBundleId: 'com.example.sushiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOoum3c2McYxVJAdRTtilbpHM3xXCERJg',
    appId: '1:355582024496:ios:79d027000c4110cccf86f5',
    messagingSenderId: '355582024496',
    projectId: 'sushi-app-e4048',
    storageBucket: 'sushi-app-e4048.appspot.com',
    iosBundleId: 'com.example.sushiApp.RunnerTests',
  );
}
